services:
  shiny:
    build: ./frontend
    ports: 
      - "3838:3838"
      
  flask:
    build: ./backend
    volumes:
      - "./camera:/camera"
    TZ: "Asia/Singapore"
    command: python3 main.py
